# Generated by Django 3.2.4 on 2021-06-09 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('available', 'Available to borrow'), ('borrowed', 'Borrowed by someone'), ('archived', 'Archived - not available anymore')], default='available', max_length=32),
        ),
        migrations.AlterField(
            model_name='song',
            name='upload',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])]),
        ),
    ]
