# Generated by Django 3.2.4 on 2021-06-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songhub', '0002_auto_20210609_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('rock', 'Rock'), ('acoustic/folk', 'Acoustic/Folk'), ('cinematic', 'Cinematic'), ('corporate/pop', 'Corporate/pop'), ('electronica', 'Electronica'), ('urban/groove', 'Urban/groove'), ('jazz', 'Jazz'), ('world/other', 'World/other')], default='rock', max_length=32),
        ),
    ]
