# Generated by Django 3.2.4 on 2021-06-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songhub', '0007_remove_song_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
