# Generated by Django 3.2.8 on 2021-11-03 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('songhub', '0009_alter_song_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
